// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvykctusxldoizqcyzzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2eWtjdHVzeGxkb2l6cWN5enpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1NDA1MDMsImV4cCI6MjA1MTExNjUwM30.WrF1L6jBXe6NtX5M74UMhP_-bJXYNL3bBU-iLfSl6WM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);